series: Basic C++
title: Dynamically Allocated Arrays
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use new[] and delete[] to create and manage arrays in heap memory.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Arrays
  - series: Basic C++
    title: The Const Keyword
  - series: Basic C++
    title: The Stack and the Heap